conveyor_serial_node:
  ros__parameters:
    port: /dev/ttyACM0
    baudrate: 115200
    serial_timeout: 1.0
    arduino_reset_delay: 2.0
    command_topic: /conveyor_cmd
    place_ready_topic: /conveyor/place_ready
    auto_command: R80
    auto_run_duration_sec: 5.0
